// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


namespace SmokeTest
{
public static class GPGSIds
{
        public const string achievement_fighter = "CgkInu2_zfgMEAIQCQ"; // <GPGSID>
        public const string achievement_moon_cutter = "CgkInu2_zfgMEAIQDA"; // <GPGSID>
        public const string achievement_gem_hunter = "CgkInu2_zfgMEAIQCg"; // <GPGSID>
        public const string achievement_escaped_the_dungeon = "CgkInu2_zfgMEAIQCA"; // <GPGSID>
        public const string achievement_speed_runner = "CgkInu2_zfgMEAIQDg"; // <GPGSID>
        public const string achievement_an_apple_a_day_keeps_the_doctor_away = "CgkInu2_zfgMEAIQDQ"; // <GPGSID>
        public const string achievement_no_hit_run = "CgkInu2_zfgMEAIQCw"; // <GPGSID>
        public const string achievement_persistent = "CgkInu2_zfgMEAIQEA";
        public const string achievement_on_track_to_completion = "CgkInu2_zfgMEAIQDw"; // <GPGSID>
        public const string achievement_addicted = "CgkInu2_zfgMEAIQEQ"; // <GPGSID>
        public const string leaderboard_hall_of_fame = "CgkInu2_zfgMEAIQEw"; // <GPGSID>
        public const string achievement_shopaholic = "CgkInu2_zfgMEAIQFA"; // <GPGSID>
        public const string achievement_i_told_you_not_to_do_this = "CgkInu2_zfgMEAIQFQ"; // <GPGSID>
        public const string achievement_but_it_is_possible = "CgkInu2_zfgMEAIQFg"; // <GPGSID>
        public const string achievement_still_on_track_to_completion = "CgkInu2_zfgMEAIQFw"; // <GPGSID>

        public const string achievement_nope = "CgkInu2_zfgMEAIQGA"; // <GPGSID>
        public const string achievement_its_dangerous_out_there = "CgkInu2_zfgMEAIQGw"; // <GPGSID>
        public const string achievement_its_a_secret_to_everybody = "CgkInu2_zfgMEAIQGQ"; // <GPGSID>
        public const string achievement_speed_fighter = "CgkInu2_zfgMEAIQGg"; // <GPGSID>
        public const string achievement_completionist = "CgkInu2_zfgMEAIQHA"; // <GPGSID>

        

        /*
        public const string event_smokingevent = "CgkInu2_zfgMEAIQBg"; // <GPGSID>
        public const string leaderboard_leaders_in_smoketesting = "CgkInu2_zfgMEAIQBQ"; // <GPGSID>
        public const string AchievementHiddenIncreamental = "CgkInu2_zfgMEAIQBA"; // <GPGSID>
        public const string AchivementToIncrement = "CgkInu2_zfgMEAIQAw"; // <GPGSID>
        public const string AchievementToReveal = "CgkInu2_zfgMEAIQAQ"; // <GPGSID>
        public const string AchivementToUnlock = "CgkInu2_zfgMEAIQAg"; // <GPGSID>
        */

    }
}
