// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

/*
public static class GPGSIds
{
        public const string achievement_fighter = "CgkInu2_zfgMEAIQCQ"; // <GPGSID>
        public const string achievement_consumer_friendly = "CgkInu2_zfgMEAIQDA"; // <GPGSID>
        public const string achievement_gem_hunter = "CgkInu2_zfgMEAIQCg"; // <GPGSID>
        public const string achievement_escaped_the_dungeon = "CgkInu2_zfgMEAIQCA"; // <GPGSID>
        public const string achievement_speed_runner = "CgkInu2_zfgMEAIQDg"; // <GPGSID>
        public const string achievement_an_apple_a_day_keeps_the_doctor_away = "CgkInu2_zfgMEAIQDQ"; // <GPGSID>
        public const string achievement_no_hit_run = "CgkInu2_zfgMEAIQCw"; // <GPGSID>
        public const string achievement_completionist = "CgkInu2_zfgMEAIQDw"; // <GPGSID>

}

*/